logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
spring:
  flyway:
    password: root
    url: jdbc:postgresql://localhost:5432/test
    user: postgres
  r2dbc:
    password: root
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
